name: devup
description: Приложение для программистов, помогающее подготовиться к техническим собеседованиям в игровой форме.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  responsive_builder: ^0.4.3
  google_fonts: ^4.0.4
  get: ^4.6.5
  font_awesome_flutter: ^10.2.1
  flutter_shapes: ^0.3.0
  provider: ^6.0.4
  flutter_feather_icons: ^2.0.0+1
  tcard: ^1.3.5
  fl_chart: ^0.55.2
  flutter_slidable: ^2.0.0
  table_calendar: ^3.0.8
  glassmorphism: ^3.0.0
  percent_indicator: ^4.2.4
  video_player: ^2.6.1
  speech_to_text: ^6.1.1
  shared_preferences: ^2.5.3
  http: ^0.13.5
  dio: ^5.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/icon/user-icon.png
    - assets/videos/Welcome_Gekko_V10.mp4
    - assets/videos/AI_Interview.MP4

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 800

    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Regular.ttf
        - asset: assets/fonts/Unbounded-Light.ttf
          weight: 300
        - asset: assets/fonts/Unbounded-Bold.ttf
          weight: 700
  
