"""init

Revision ID: 990071f2846c
Revises: 
Create Date: 2025-05-16 04:05:50.015584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990071f2846c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theories')
    # ### end Alembic commands ###
