services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: devup
      POSTGRES_PASSWORD: devup
      POSTGRES_DB: devup
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devup"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7
    ports: ["6379:6379"]

  analyze-service:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: .env
    ports: ["8000:8000"]
